name: Labeler
run-name: Labeler workflow initiated by ${{ github.actor }}

on: 
  pull_request:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: actions/checkout@v3
      - name: Label PR size
        id: label-pr-size
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '50'
          m_max_size: '200'
          l_max_size: '450'
          fail_if_xl: 'true'
          comment_if_xl: 'true'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
      - name: Is the PR extra-large?
        if: steps.label-pr-size.outputs.pr_is_xl
        run: |
          echo "${{ steps.label-pr-size.outputs.pr_is_xl }}"
          echo "PR is xl."
      - name: Is the PR not extra-large?
        if: !steps.label-pr-size.outputs.pr_is_xl
        run: |
          echo "${{ steps.label-pr-size.outputs.pr_is_xl }}"
          echo "PR is not xl."
